#!/usr/bin/python
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

import torch

TEST_PARAMS = {
    "decode_first": {
        "Testcase_Name": [None],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [48],
        "S1": [2],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [1024],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["CSA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
    },
    "prefill_first": {
        "Testcase_Name": [None],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [1],
        "S1": [8192],
        "S2": [8192],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [1],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [0],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["SWA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
    },
    "ori_sparse_decode": {
        "Testcase_Name": [None],
        "layout_q": ["BSND", "TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [10],
        "S1": [15],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K1": [124, 64],
        "K": [128],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1, 2],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["random"],  # fullK random
        "ori_sparse_indices_mode": ["full"],  # full random
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
    },
    "ori_cmp_sparse_decode": {
        "Testcase_Name": [None],
        "layout_q": ["BSND", "TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [4],
        "S1": [4],
        "S2": [16],
        "N1": [64, 128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "K1": [128],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_SPARSE", "ORI_CMP_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["fullK"],  # fullK random
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],  # full random
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
    },
    "ori_sparse_decode_bsnd": {
        "Testcase_Name": [None],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [10],
        "S1": [15],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K1": [64, 32],
        "K": [128],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["random"],
        "ori_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
    },
    "ori_cmp_sparse_decode_tnd": {
        "Testcase_Name": [None],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [4],
        "S1": [4],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [256],
        "K1": [512],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [[0, 4, 8, 12, 16]],
        "seqused_ori_kv": [[100, 111, 96, 1]],
        "seqused_cmp_kv": [[25, 27, 24, 0]],
        "cu_seqlens_ori_kv": [[0, 128, 256, 384, 512]],
        "cu_seqlens_cmp_kv": [[0, 32, 64, 96, 128]],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0, 3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_CMP_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
    },
    "ori_cmp_sparse_decode_with_topk": {
        "Testcase_Name": [None],
        "layout_q": ["BSND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [256],
        "K1": [128],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0, 3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_CMP_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [[64, 32, 48, 16]],
        "cmp_topk_length": [[32, 16, 24, 8]],
        "return_softmax_lse": [True],
    },
    "load_4096_swa_tnd_pa": {
        "Testcase_Name": ["bc_load_4096_swa_tnd_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [4096],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [0],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[4096]],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [1],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["SWA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_8192_hca_tnd_tnd": {
        "Testcase_Name": ["bc_load_8192_hca_tnd_tnd"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [6554],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [0],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[6554]],
        "seqused_cmp_kv": [[1638]],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [3],
        "cmp_mask_mode": [3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["HCA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_2048_csa_bsnd_bsnd": {
        "Testcase_Name": ["bc_load_2048_csa_bsnd_bsnd"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [1639],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [409],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[1639]],
        "seqused_cmp_kv": [[409]],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [[3]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["CSA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_5120_ori_sparse_bsnd_pa": {
        "Testcase_Name": ["bc_load_5120_ori_sparse_bsnd_pa"],
        "layout_q": ["BSND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [5120],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K1": [5120],
        "K": [0],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[5120]],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["random"],
        "ori_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_4096_ori_cmp_sparse_tnd_pa": {
        "Testcase_Name": ["bc_load_4096_ori_cmp_sparse_tnd_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [3277],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [819],
        "K1": [3277],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[3277]],
        "seqused_cmp_kv": [[819]],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_CMP_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [[64, 32, 48, 16]],
        "cmp_topk_length": [[32, 16, 24, 8]],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "bc_shape_change_valid_sparse_indices": {
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [1],
        "S2": [3072],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [48],
        "block_num2": [12],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[1, 1]],
        "cu_seqlens_q": [[0, 1, 2]],
        "seqused_ori_kv": [[2049, 2049]],
        "seqused_cmp_kv": [[512, 512]],
        "cu_seqlens_ori_kv": [[0, 3072, 6144]],
        "cu_seqlens_cmp_kv": [[0, 768, 1536]],
        "cmp_residual_kv": [[1, 1]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "actlen_mode": ["full"],
        "ori_win_right": [0],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "topk_value_mode": [1],
        "return_softmax_lse": [True],
        "q_datarange": [[-5.0, 5.0]],
        "ori_kv_datarange": [[-5.0, 5.0]],
        "cmp_kv_datarange": [[-5.0, 5.0]],
        "ori_kv_topk_mode": ["no"],
        "cmp_kv_topk_mode": ["no"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "K1": [None],
        "batch_consistency": [True],
        "template_run_mode": ["CSA"],
        "Testcase_Name": ["bc_shape_change_valid_sparse_indices"],
        "batch_consistency_seed": [42],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [None],
        "batch_consistency_shape_change": [[1, 1]],
        "T1": [2],
        "T2": [6144],
        "T3": [1536],
    },
    "bc_ori_cmp_reduction_boundary": {
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [3],
        "S1": [2],
        "S2": [8193],
        "N1": [32],
        "N2": [1],
        "D": [512],
        "K": [0],
        "block_num1": [66],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2, 2]],
        "cu_seqlens_q": [[0, 2, 4, 6]],
        "seqused_ori_kv": [[8193, 0, 10]],
        "seqused_cmp_kv": [[2048, 0, 2]],
        "cu_seqlens_ori_kv": [[0, 8193, 8193, 8203]],
        "cu_seqlens_cmp_kv": [[0, 2048, 2048, 2050]],
        "cmp_residual_kv": [[1, 0, 2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [3],
        "ori_win_left": [-1],
        "actlen_mode": ["full"],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "topk_value_mode": [1],
        "return_softmax_lse": [False],
        "q_datarange": [[-5.0, 5.0]],
        "ori_kv_datarange": [[-5.0, 5.0]],
        "cmp_kv_datarange": [[-5.0, 5.0]],
        "ori_kv_topk_mode": ["no"],
        "cmp_kv_topk_mode": ["no"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "K1": [None],
        "batch_consistency": [True],
        "template_run_mode": ["HCA"],
        "Testcase_Name": ["bc_ori_cmp_reduction_boundary"],
        "batch_consistency_seed": [42],
        "batch_consistency_order": [[2, 0, 1]],
        "batch_consistency_batch_split": [[1, 2]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
        "T1": [6],
        "T2": [8203],
        "T3": [2050],
    },
    # 有效 ORI=CMP=2049，规约块大小256，各9块；CMP起点必须从基本块编号17更新为9。
    # 单batch可暴露未更新CMP起点导致行尾误判、漏掉FD规约任务的问题。
    "bc_cmp_start_reduction_boundary": {
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [1],
        "S1": [1],
        "S2": [8196],
        "N1": [32],
        "N2": [1],
        "D": [512],
        "K": [0],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[1]],
        "cu_seqlens_q": [[0, 1]],
        "seqused_ori_kv": [[8196]],
        "seqused_cmp_kv": [[2049]],
        "cu_seqlens_ori_kv": [[0, 8196]],
        "cu_seqlens_cmp_kv": [[0, 2049]],
        "cmp_residual_kv": [[0]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [2048],
        "actlen_mode": ["full"],
        "ori_win_right": [0],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "topk_value_mode": [1],
        "return_softmax_lse": [True],
        "q_datarange": [[-5.0, 5.0]],
        "ori_kv_datarange": [[-5.0, 5.0]],
        "cmp_kv_datarange": [[-5.0, 5.0]],
        "ori_kv_topk_mode": ["no"],
        "cmp_kv_topk_mode": ["no"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "K1": [None],
        "batch_consistency": [True],
        "template_run_mode": ["HCA"],
        "Testcase_Name": ["bc_cmp_start_reduction_boundary"],
        "batch_consistency_seed": [42],
        "batch_consistency_order": [None],
        "batch_consistency_batch_split": [None],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [None],
        "batch_consistency_shape_change": [[1, 1]],
        "T1": [1],
        "T2": [8196],
        "T3": [2049],
    },
    "bc_zero_row_aiv_sync": {
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [None],
        "B": [8],
        "S1": [512],
        "S2": [8192],
        "T1": [4096],
        "N1": [1],
        "N2": [1],
        "D": [512],
        "K": [0],
        "block_num1": [512],
        "block_num2": [0],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[512, 512, 512, 512, 512, 512, 512, 512]],
        "cu_seqlens_q": [[0, 512, 1024, 1536, 2048, 2560, 3072, 3584, 4096]],
        "seqused_ori_kv": [[8192, 8192, 8192, 8192, 8192, 8192, 8192, 8192]],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [
            [0, 8192, 16384, 24576, 32768, 40960, 49152, 57344, 65536]
        ],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [1],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [0],
        "ori_win_left": [8100],
        "actlen_mode": ["full"],
        "ori_win_right": [0],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "topk_value_mode": [1],
        "return_softmax_lse": [False],
        "q_datarange": [[-5.0, 5.0]],
        "ori_kv_datarange": [[-5.0, 5.0]],
        "cmp_kv_datarange": [[-5.0, 5.0]],
        "ori_kv_topk_mode": ["no"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "T2": [65536],
        "T3": [None],
        "K1": [None],
        "batch_consistency": [True],
        "template_run_mode": ["SWA"],
        "Testcase_Name": ["bc_zero_row_aiv_sync"],
        "batch_consistency_seed": [42],
        "batch_consistency_order": [[3, 4, 6, 7, 2, 5, 0, 1]],
        "batch_consistency_batch_split": [[4, 4]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[256, 256]],
        "batch_consistency_shape_change": [[511, 2]],
    },
    "bc_reduction_unit_boundary": {
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [None],
        "B": [3],
        "S1": [2],
        "S2": [8194],
        "T1": [6],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [0],
        "block_num1": [66],
        "block_num2": [0],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2, 2]],
        "cu_seqlens_q": [[0, 2, 4, 6]],
        "seqused_ori_kv": [[8194, 0, 10]],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [[0, 8194, 8194, 8204]],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [1],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "actlen_mode": ["full"],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "topk_value_mode": [1],
        "return_softmax_lse": [False],
        "q_datarange": [[-5.0, 5.0]],
        "ori_kv_datarange": [[-5.0, 5.0]],
        "cmp_kv_datarange": [[-5.0, 5.0]],
        "ori_kv_topk_mode": ["no"],
        "cmp_kv_topk_mode": ["no"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "T2": [8204],
        "T3": [None],
        "K1": [None],
        "batch_consistency": [True],
        "template_run_mode": ["SWA"],
        "Testcase_Name": ["bc_reduction_unit_boundary"],
        "batch_consistency_seed": [42],
        "batch_consistency_order": [[1, 0, 2]],
        "batch_consistency_batch_split": [[1, 2]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 2]],
    },
    # 原始 ORI/CMP 长度超过各自索引宽度，FA/FD 应使用截断后的有效长度。
    "bc_topk_length_exceeds_index_width": {
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [4],
        "S1": [4],
        "S2": [8192],
        "T1": [16],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [1024],
        "block_num1": [256],
        "block_num2": [64],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[4, 4, 4, 4]],
        "cu_seqlens_q": [[0, 4, 8, 12, 16]],
        "seqused_ori_kv": [[8192, 8192, 8192, 8192]],
        "seqused_cmp_kv": [[2048, 2048, 2048, 2048]],
        "cu_seqlens_ori_kv": [[0, 8192, 16384, 24576, 32768]],
        "cu_seqlens_cmp_kv": [[0, 2048, 4096, 6144, 8192]],
        "cmp_residual_kv": [[0, 0, 0, 0]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "actlen_mode": ["full"],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "topk_value_mode": [1],
        "return_softmax_lse": [False],
        "q_datarange": [[-2.0, 2.0]],
        "ori_kv_datarange": [[-2.0, 2.0]],
        "cmp_kv_datarange": [[-2.0, 2.0]],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [
            [
                4096,
                4096,
                4096,
                4096,
                8192,
                4096,
                4096,
                4096,
                4096,
                4096,
                4096,
                4096,
                4096,
                4096,
                4096,
                4096,
            ]
        ],
        "cmp_topk_length": [
            [
                100,
                1000,
                1024,
                1024,
                1733,
                1011,
                1024,
                1024,
                1024,
                1024,
                1024,
                1024,
                1024,
                1024,
                1024,
                1,
            ]
        ],
        "T2": [32768],
        "T3": [8192],
        "K1": [4096],
        "batch_consistency": [True],
        "Testcase_Name": ["bc_topk_length_exceeds_index_width"],
        "batch_consistency_seed": [42],
        "batch_consistency_order": [[2, 0, 3, 1]],
        "batch_consistency_batch_split": [[2, 2]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[2, 2]],
        "batch_consistency_shape_change": [[3, 1]],
        "template_run_mode": ["ORI_CMP_SPARSE"],
    },
}

ENABLED_PARAMS = [
    TEST_PARAMS["decode_first"],
    TEST_PARAMS["bc_shape_change_valid_sparse_indices"],
    TEST_PARAMS["bc_ori_cmp_reduction_boundary"],
    TEST_PARAMS["bc_cmp_start_reduction_boundary"],
    TEST_PARAMS["bc_zero_row_aiv_sync"],
    TEST_PARAMS["bc_reduction_unit_boundary"],
    TEST_PARAMS["bc_topk_length_exceeds_index_width"],
]
